version: '3'
services:
  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofrontend
    networks:
      - my-network
  todofront:
    image: todofrontend
    ports: ['3000']
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todobackend
    networks:
      - my-network
  todoback:
    image: todobackend
    ports: ['3001']
    networks:
      - my-network
networks:
  my-network:
